// All available Tanzanian locations/regions
export const AVAILABLE_LOCATIONS: string[] = [
    "ARUSHA",
    "DAR ES SALAAM",
    "DODOMA",
    "GEITA",
    "IRINGA",
    "KAGERA",
    "KATAVI",
    "KIGOMA",
    "KILIMANJARO",
    "LINDI",
    "MANYARA",
    "MARA",
    "MBEYA",
    "MOROGORO",
    "MTWARA",
    "MWANZA",
    "NJOMBE",
    "PEMBA",
    "PWANI",
    "RUKWA",
    "RUVUMA",
    "SHINYANGA",
    "SIMIYU",
    "SINGIDA",
    "SONGWE",
    "TABORA",
    "TANGA",
    "ZANZIBAR",
]
