// Facebook tags for social media posts
export const FACEBOOK_TAGS = [
    "@Tume Ya Maendeleo Ya Ushirika",
    "@Bodi ya Usimamizi wa Stakabadhi za Ghala-WRRB",
    "@Wizara ya Fedha",
    "@Wizara ya Viwanda na Biashara",
    "@Ofisi ya Rais - Tamisemi",
    "@Capital Market & Security Authority",
    "@Bank of Tanzania",
    "@Samia Suluhu Hassan ",
    "@Ikulu Mawasiliano",
]

// Instagram handles for social media posts
export const INSTAGRAM_TAGS = [
    "@copra_tz",
    "@ushirika_tcdc",
    "@wrrbwrs",
    "@urtmof",
    "@viwandabiashara",
    "@ortamisemi",
    "@cmsa.go.tz",
    "@bankoftanzania_",
    "@samia_suluhu_hassan",
    "@ikulu_mawasiliano",
]

// Hashtags for commodity price posts
export const COMMODITY_PRICE_HASHTAGS = [
    "#sesame",
    "#chickpeas",
    "#coffee",
    "#soya",
    "#kahawa",
    "#commodityexchangemarkets",
    "#commoditiesexchange",
    "#agriculture",
    "#commoditiestrading",
    "#seller",
    "#commoditytraders",
    "#agriculturalcommodityexhange",
    "#farmersmarket",
    "#onlinetradingsystem",
    "#agriculturalcommodityexchange",
    "#onlinetrading",
    "#commoditytrader",
    "#traders",
    "#tradingcommodities",
    "#sesameseeds",
    "#OnlineTradingPlatform",
]

// Hashtags for social media posts
export const HASHTAGS = [
    "#oilseeds",
    "#buyers",
    "#trading",
    "#commodityexchangemarkets",
    "#commoditiesexchange",
    "#agriculture",
    "#commoditiestrading",
    "#tanzania",
    "#commoditytraders",
    "#agriculturalcommodityexhange",
    "#farmersmarket",
    "#onlinetradingsystem",
    "#agriculturalcommodityexchange",
    "#onlinetrading",
    "#commoditytrader",
    "#tanzaniatrader",
    "#tradingcommodities",
    "#OnlineTradingPlatform",
    "#buyer",
    "#commoditiesmarket",
    "#commodities",
    "#buyersmarket",
    "#TradingCommodities",
    "#trader",
    "#SellersMarket",
    "#online",
    "#agriculturalcommodities",
    "#farmer",
]
